name: assets_transformation_presentation
description: "a presentation about state transformation for flutter vienna"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  dart_code_viewer_x: ^1.0.1
  dart_style: ^2.3.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_deck: ^0.14.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  graphite: ^1.1.2
  intl: any
  rive: ^0.13.5
  vector_graphics: 1.1.11+1

dev_dependencies:
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  vector_graphics_compiler: 1.1.11+1
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/rive/
    - path: assets/svg/youtrust_full_logo.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/svg/hessen.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/svg/hessen_2.svg


  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/GraphikSemibold.otf
          weight: 600
        - asset: assets/fonts/GraphikMedium.otf
          weight: 500
        - asset: assets/fonts/GraphikRegular.otf
          weight: 400

flutter_gen:
  output: lib/generated
  line_length: 80
  integrations:
    flutter_svg: true
